In [1]:
import torch 
import numpy as np
import pandas as pd
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('music_train.csv',index_col='id')
df=df.fillna(0)
df

release_date    dating  violence  world/life  night/time  \
id                                                                
0            2014.0  0.001049  0.000254    0.078057    0.282523   
1            1962.0  0.059132  0.000000    0.000000    0.001836   
2            1969.0  0.027451  0.085989    0.039760    0.001288   
3            2004.0  0.050993  0.000000    0.000000    0.000477   
4            1992.0  0.000551  0.028702    0.000000    0.069748   
...             ...       ...       ...         ...         ...   
17738        2011.0  0.006589  0.000000    0.021678    0.000000   
17739        2002.0  0.008281  0.000000    0.071316    0.025514   
17740        1982.0  0.000710  0.388212    0.000615    0.078012   
17741           0.0  0.027210  0.117397    0.004522    0.296837   
17742        1992.0  0.000120  0.002267    0.439454    0.000999   

       shake the audience  family/gospel  romantic  communication   obscene  \
id                                                                            
0                0.000000       0.000654  1.109899       3.484935  0.360515   
1                0.000737       0.000000  0.758840       0.000000  0.018112   
2                0.001424       0.000857  0.545408       0.016914  0.015750   
3                0.008157       0.002800  0.000000       0.003703  2.603917   
4                0.008735       0.000625  0.014364       0.253022  0.007968   
...                   ...            ...       ...            ...       ...   
17738            0.007656       0.000552  0.000478       0.004078  3.903704   
17739            0.130170       0.013863  0.016706       0.000000  6.439481   
17740            0.002473       0.000000  2.024262       0.998057  0.018277   
17741            0.002955       0.002310  0.000000       0.431139  0.933112   
17742            0.015221       0.071824  0.023428       0.000000  0.002299   

       ...  feelings  danceability  loudness  acousticness  instrumentalness  \
id     ...                                                                     
0      ...  0.001021      0.673433  0.753102      0.002560          0.001046   
1      ...  0.001697      0.690740  0.678925      0.785480          0.001009   
2      ...  0.000000      0.186294  0.404628      0.890527          0.060886   
3      ...  0.067061      0.499643  0.685085      0.640129          0.163850   
4      ...  0.000000      0.407141  0.616982      0.030576          0.000000   
...    ...       ...           ...       ...           ...               ...   
17738  ...  0.265363      0.699730  0.753779      0.510676          0.000624   
17739  ...  0.001289      0.758641  0.716034      0.000000          0.000000   
17740  ...  0.003411      0.512652  0.732854      0.017187          0.491014   
17741  ...  0.000000      0.594225  0.754684      0.005137          0.000091   
17742  ...  0.000000      0.465397  0.735680      0.649489          0.000000   

        valence     energy       age  genre  topic  
id                                                  
0      0.040567  48.364265  0.085714      4    2.0  
1      0.743203  28.200609  0.828571      1    7.0  
2      0.093003  13.145639  0.728571      4    0.0  
3      0.648084  62.663152  0.228571      0    5.0  
4      0.000000  48.641741  0.400000      1    1.0  
...         ...        ...       ...    ...    ...  
17738  0.271493  74.876372  0.128571      4    3.0  
17739  0.915961  50.097257  0.257143      5    3.0  
17740  0.606948  92.972488  0.542857      0    6.0  
17741  0.456820  74.079139  0.557143      4    2.0  
17742  0.466926  54.085364  0.400000      4    7.0  

[17743 rows x 26 columns]

In [3]:
x=(df.iloc[:,1:24]) 
x['topic']=df['topic']
x
 

dating  violence  world/life  night/time  shake the audience  \
id                                                                      
0      0.001049  0.000254    0.078057    0.282523            0.000000   
1      0.059132  0.000000    0.000000    0.001836            0.000737   
2      0.027451  0.085989    0.039760    0.001288            0.001424   
3      0.050993  0.000000    0.000000    0.000477            0.008157   
4      0.000551  0.028702    0.000000    0.069748            0.008735   
...         ...       ...         ...         ...                 ...   
17738  0.006589  0.000000    0.021678    0.000000            0.007656   
17739  0.008281  0.000000    0.071316    0.025514            0.130170   
17740  0.000710  0.388212    0.000615    0.078012            0.002473   
17741  0.027210  0.117397    0.004522    0.296837            0.002955   
17742  0.000120  0.002267    0.439454    0.000999            0.015221   

       family/gospel  romantic  communication   obscene     music  ...  \
id                                                                 ...   
0           0.000654  1.109899       3.484935  0.360515  0.016644  ...   
1           0.000000  0.758840       0.000000  0.018112  0.658993  ...   
2           0.000857  0.545408       0.016914  0.015750  0.277632  ...   
3           0.002800  0.000000       0.003703  2.603917  0.005438  ...   
4           0.000625  0.014364       0.253022  0.007968  3.980988  ...   
...              ...       ...            ...       ...       ...  ...   
17738       0.000552  0.000478       0.004078  3.903704  0.021088  ...   
17739       0.013863  0.016706       0.000000  6.439481  0.004837  ...   
17740       0.000000  2.024262       0.998057  0.018277  0.018898  ...   
17741       0.002310  0.000000       0.431139  0.933112  0.001832  ...   
17742       0.071824  0.023428       0.000000  0.002299  0.462317  ...   

        sadness  feelings  danceability  loudness  acousticness  \
id                                                                
0      0.022435  0.001021      0.673433  0.753102      0.002560   
1      0.242728  0.001697      0.690740  0.678925      0.785480   
2      0.360503  0.000000      0.186294  0.404628      0.890527   
3      0.307565  0.067061      0.499643  0.685085      0.640129   
4      0.047896  0.000000      0.407141  0.616982      0.030576   
...         ...       ...           ...       ...           ...   
17738  0.045660  0.265363      0.699730  0.753779      0.510676   
17739  0.001454  0.001289      0.758641  0.716034      0.000000   
17740  0.002084  0.003411      0.512652  0.732854      0.017187   
17741  0.000202  0.000000      0.594225  0.754684      0.005137   
17742  0.224749  0.000000      0.465397  0.735680      0.649489   

       instrumentalness   valence     energy       age  topic  
id                                                             
0              0.001046  0.040567  48.364265  0.085714    2.0  
1              0.001009  0.743203  28.200609  0.828571    7.0  
2              0.060886  0.093003  13.145639  0.728571    0.0  
3              0.163850  0.648084  62.663152  0.228571    5.0  
4              0.000000  0.000000  48.641741  0.400000    1.0  
...                 ...       ...        ...       ...    ...  
17738          0.000624  0.271493  74.876372  0.128571    3.0  
17739          0.000000  0.915961  50.097257  0.257143    3.0  
17740          0.491014  0.606948  92.972488  0.542857    6.0  
17741          0.000091  0.456820  74.079139  0.557143    2.0  
17742          0.000000  0.466926  54.085364  0.400000    7.0  

[17743 rows x 24 columns]

In [4]:
 y=pd.DataFrame(df['genre'])
 y=y.squeeze(1)
 y

id
0        4
1        1
2        4
3        0
4        1
        ..
17738    4
17739    5
17740    0
17741    4
17742    4
Name: genre, Length: 17743, dtype: int64

In [5]:
x=torch.tensor(x.values, dtype=torch.float32)
y=torch.tensor(y.values)
x,y

(tensor([[1.0488e-03, 2.5450e-04, 7.8057e-02,  ..., 4.8364e+01, 8.5714e-02,
          2.0000e+00],
         [5.9132e-02, 0.0000e+00, 0.0000e+00,  ..., 2.8201e+01, 8.2857e-01,
          7.0000e+00],
         [2.7451e-02, 8.5989e-02, 3.9760e-02,  ..., 1.3146e+01, 7.2857e-01,
          0.0000e+00],
         ...,
         [7.0995e-04, 3.8821e-01, 6.1515e-04,  ..., 9.2972e+01, 5.4286e-01,
          6.0000e+00],
         [2.7210e-02, 1.1740e-01, 4.5223e-03,  ..., 7.4079e+01, 5.5714e-01,
          2.0000e+00],
         [1.1989e-04, 2.2674e-03, 4.3945e-01,  ..., 5.4085e+01, 4.0000e-01,
          7.0000e+00]]),
 tensor([4, 1, 4,  ..., 0, 4, 4]))

In [6]:
val_percent = 0.05
input_size = 24
hidden_size = 13
learning_rate = 0.001
num_epochs = 1000
num_classes = 7

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=val_percent, random_state=42)

In [8]:
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 =  nn.Linear(hidden_size, hidden_size)
        self.fc4 =  nn.Linear(hidden_size, num_classes)

    
    def forward(self, x):
        out = self.fc1(x)
        out = F.relu(out)
        out = self.fc2(out)
        out = F.relu(out)
        out = self.fc3(out)
        out = self.fc4(out)
        return out


model = NeuralNet(input_size, hidden_size, num_classes)
model

NeuralNet(
  (fc1): Linear(in_features=24, out_features=13, bias=True)
  (fc2): Linear(in_features=13, out_features=13, bias=True)
  (fc3): Linear(in_features=13, out_features=13, bias=True)
  (fc4): Linear(in_features=13, out_features=7, bias=True)
)

In [9]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [10]:
for epoch in range(num_epochs): 
    X = torch.FloatTensor(X_train)
    Y = torch.LongTensor(Y_train)
    out = model(X)
    loss = criterion(out, Y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
     
    acc = 100 * torch.sum(Y==torch.max(out.data, 1)[1]).double() / len(Y)
    print ('Epoch [{}/{}] , Loss: {:.4f} , Accuracy: {:.4f}' .format(epoch+1, num_epochs , loss.item(), acc.item() ))
    

ss: 1.5793 , Accuracy: 35.5918
Epoch [617/1000] , Loss: 1.5792 , Accuracy: 35.5088
Epoch [618/1000] , Loss: 1.5791 , Accuracy: 35.5918
Epoch [619/1000] , Loss: 1.5790 , Accuracy: 35.6215
Epoch [620/1000] , Loss: 1.5788 , Accuracy: 35.5859
Epoch [621/1000] , Loss: 1.5787 , Accuracy: 35.6096
Epoch [622/1000] , Loss: 1.5786 , Accuracy: 35.6155
Epoch [623/1000] , Loss: 1.5785 , Accuracy: 35.6155
Epoch [624/1000] , Loss: 1.5783 , Accuracy: 35.6571
Epoch [625/1000] , Loss: 1.5782 , Accuracy: 35.6274
Epoch [626/1000] , Loss: 1.5781 , Accuracy: 35.6927
Epoch [627/1000] , Loss: 1.5779 , Accuracy: 35.6630
Epoch [628/1000] , Loss: 1.5778 , Accuracy: 35.6571
Epoch [629/1000] , Loss: 1.5777 , Accuracy: 35.7105
Epoch [630/1000] , Loss: 1.5776 , Accuracy: 35.7164
Epoch [631/1000] , Loss: 1.5775 , Accuracy: 35.7164
Epoch [632/1000] , Loss: 1.5773 , Accuracy: 35.7342
Epoch [633/1000] , Loss: 1.5772 , Accuracy: 35.7283
Epoch [634/1000] , Loss: 1.5771 , Accuracy: 35.7639
Epoch [635/1000] , Loss: 1.5770 ,

In [11]:
X_test = torch.FloatTensor(X_test)
Y_test = torch.LongTensor(Y_test)
out = model(X_test)
predicted = torch.max(out.data, 1)[1]
print('Accuracy of the network %.4f %%' % (100 * torch.sum(Y_test==predicted).double() / len(Y_test)))

Accuracy of the network 37.6126 %


In [12]:
test=pd.read_csv('music_test.csv',index_col='id')
test=test.fillna(0)
test=(test.iloc[:,1:25]) 
test=torch.tensor(test.values, dtype=torch.float32)
out = model(test)
predicted = torch.max(out.data, 1)[1]
predicted


tensor([1, 4, 2,  ..., 6, 1, 4])

In [13]:
submission=pd.DataFrame(predicted)
id=pd.read_csv('music_test.csv')
submission['id']=id['id']
submission=submission.set_index('id')
submission.columns=['genre']
submission.to_csv('assignment_submission.csv')